apiVersion: v1
kind: Service
metadata:
  name: front-end
  
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    name: result-app-pod
    app: example-voting-app
