apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: example-voting-app
spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: example-voting-app
    spec:
      containers:
        - name: worker-app
          image: prabhavagrawal/worker-app
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod-pod
      app: example-voting-app
