apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: example-voting-app
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: example-voting-app
    spec:
      containers:
        - name: db
          image: postgres:9.4
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
           - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: example-voting-app
